### ISSUE TITLE
I'd like to join your project! 

### ISSUE THREAD

**Issue by annielarkins** [BYUCS452F2021/Q2#1]
Why I am interested: I spent two semesters working as a TA for CS 142 and am on my second semester as a CS 324 TA. I have witnessed firsthand many of the pain points of the current help queue system both on the TA and the student end. With CS 324, we aren’t even using the help queue and instead attempting to use a slack channel. I would love to help improve the current system to benefit myself, my fellow TA’s, and all students in CS classes.

How I can contribute: I have experience using Azure products such as virtual machines, Azure Functions, Databricks, CosmosDB, and Azure Data Explorer if we want to experiment with using those. I also have some basic web programming experience. Beyond this, I am a fast learner and willing to pick up lots of new skills to be able to best contribute to this project. I also love the marketing and operational side of projects and would love to help with meeting with customers, design, marketing, and presenting our ideas.

**Comment by spencerteiknsmith** [comment]
Hey Annie,
I'd be pleased as punch to have you on the Q2 team! Sorry for the delay in responding to your interest (the last week has been hectic for me). I'll pick up the conversation in the class slack, but figured it might be good to send a ping here.
