### ISSUE TITLE
I would like to join

### ISSUE THREAD

**Issue by derekanderson98** [BYUCS452F2021/Q2#2]
As a CS142 TA I use the help queue a lot and would be interested in improving things for myself and future TAs. I would mostly prefer to work with the database management and business logic, but can contribute anywhere needed. My contributions would likely be most valuable in backend, as I am far less familiar with frontend development.

-Derek Anderson

**Comment by spencerteiknsmith** [comment]
Hey Derek,
I'd be pleased as punch to have you on the Q2 team! Sorry for the delay in responding to your interest (the last week has been hectic for me). I'll pick up the conversation in discord, but figured it might be good to send a ping here.
