### ISSUE TITLE
I would like to join!

### ISSUE THREAD

**Issue by ryanrking** [BYUCS452F2021/Q2#3]
Why I'm interested: I harbor a healthy hatred for the current help queue system, as I'm sure you do too. I have a roommate who TA's in the IT department, so I've had a lot of opportunities to contrast their pretty good Help Queue with our own not-so-great one. I also really like the idea of creating something that will be in use for a long time, sparing students from sharing our suffering long after we've left. Finally, I've been considering learning Rust for a while now, so working on a project with a Rust back-end sounds extremely valuable to me.

How I can contribute: I'm fresh out of CS260, so I have some solid experience in mobile- and web-friendly design, as well as development using Vue.js, HTML, CSS, JavaScript, and MongoDB. Additionally, I'm a fast learner and am excited to learn new skills that will help in creating this queue system. I'm hard-working and easy to work with, so you won't ever have to worry about me being the one in the group who isn't pulling their weight. I'm willing to work wherever I'm needed most.

**Comment by spencerteiknsmith** [comment]
Hey Ryan,
I'd be pleased as punch to have you on the Q2 team! Sorry for the delay in responding to your interest (the last week has been hectic for me). I'll pick up the conversation in the class slack, but figured it might be good to send a ping here.
