### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by irvinmdoza** [BYUCS452F2021/Q2#4]
Hello!
My name is Irvin Mendoza and I'd like to contribute to this project.  Although I have not been a TA before, I have had to deal with the pesky current queue system as a student and would be excited to help contribute to making the experience less painful/stressful for future students.  What I can offer is my experience in building web applications, both front end (with responsive design) and back end as well as my experience working with databases and APIs at the BYU Office of Information Technology.

**Comment by spencerteiknsmith** [comment]
Hey Irvin,
It looks like you've already joined a different project. Let me know if that's incorrect by commenting on this issue - otherwise, I'll just close it in a few days.

**Comment by irvinmdoza** [comment]
Hello yes, I have joined a project already.  Thank you
