### ISSUE TITLE
Hi I'm Interested!

### ISSUE THREAD

**Issue by johnny123214133** [BYUCS452F2021/Q2#5]
Hi, I’m Zach and I remember how infuriating the help queues can be.  I have experience with MySQL and DynamoDB in case those are the databases we want to use.  As part of past internships I have experience with basic web development languages, and within the CS program I’ve built Android apps.  I’ve also worked a little with PHP, so if we need to poke around in the current queue’s codebase, I may be of help there.

**Comment by spencerteiknsmith** [comment]
Hey Zach,
It looks like you've already joined a different project. Let me know if that's incorrect by commenting on this issue - otherwise, I'll just close it in a few days.
