### ISSUE TITLE
I'm interested in helping solve the queue problem!

### ISSUE THREAD

**Issue by cjbeacon** [BYUCS452F2021/Q2#6]
Hi I'm Caleb Johnson, I'm interested in helping with this project having dealt with the help queue in the past as a student. I like solving problems that have real impacts on people. I've taken CS260 and have understanding of some web technologies including some familiarity with MongoDB. During my internship over the last summer, I worked a lot with the UX designers on my team learning to be better at identifying user experience issues in software.

**Comment by spencerteiknsmith** [comment]
Hey Caleb,
It looks like you've already joined a different project. Let me know if that's incorrect by commenting on this issue - otherwise, I'll just close it in a few days.

**Comment by cjbeacon** [comment]
I saw this project had a lot of people jumping on, so I decided to hop in another. Good luck with the project!
