### ISSUE TITLE
Sign me UP!

### ISSUE THREAD

**Issue by vech2514** [BYUCS452F2021/Q2#7]
Hey I'm Ben White. I remember the clunkiness of the TA help queue all too well and believe that it'd be really fun to do it better. I've held several school and professional positions as a web application developer. I have a lot of experience with HTML, CSS, JavaScript, Java, C#, SQL and NoSQL Databases. I'm the resident expert at SQL and NoSQL databases at my current job at the Center for Family History and Genealogy here at BYU which is 60% SQL databases (but transitioning to NoSQL). Additionally, I'm a very self-motivated person when it comes to projects so not only will I get my shares done but I'll be a great help in driving discussion and problem solving as a team.

**Comment by spencerteiknsmith** [comment]
Hey Ben,
It looks like you've already joined a different project. Let me know if that's incorrect by commenting on this issue - otherwise, I'll just close it in a few days.
